### ISSUE TITLE
You can omit index.html when you link to a folder

### ISSUE THREAD

**Issue by gorazd** [gorazd/swiss-poster#1]
Instead of **linking** to:
`poster/poster-1/index.html`
you can link like this:
`poster/poster-1`

CSS
```css
.wrapper{
    max-width: 595px;
    min-height: 842px;
    margin: auto;
    padding: 1em;
    display: grid;
    grid-template-rows: 75% 25%;
    border: 2px solid darkgrey;
}
```

@adelerossi Help me fix the links
@Andreatorromeo What do you think of the css
